name: CI - Lint Shell Scripts

on:
  push:
    branches:
      - main
  pull_request:
      - main

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck