name: Go course CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ShellCheck:
    runs-on: ubuntu-latest@22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  shfmt:
    runs-on: ubuntu-latest@22.04
    steps:
      - name: shfmt
        uses: mfinelli/setup-shfmt@v3